### ISSUE TITLE
Attachment icon not visible

### ISSUE THREAD

**Issue by Gabryxx7** [tothpsk/mailspring-theme-pop-os#4]
Hyia, lovinf your theme and I'm using it on my Mailspring :)
I noticed the attachment icon was not visible since the original icon is pretty much same color as the background.

Fixed adding these lines in the `ui-variable.less`:
```less
.thread-icon:not(.thread-icon-unread):not(.thread-icon-star) {
    -webkit-filter: invert(100%);
  }
  img.content-dark {
    -webkit-filter: invert(100%);
  }
  img.content-light {
    -webkit-filter: invert(100%);
  }
  
  .mail-label {
    -webkit-filter: contrast(110%) brightness(85%);
  }
```

Hope this helps :)
Cheers!
